export const dataHeaders = [
  {
    label: 'ID',
    name: 'id',
    position: 1,
    visible: true,
    sortable: true,
    editable: true,
    resizable: true,
    filterable: true,
    dataType: 'string',
    fieldType: 'input',
    api: 'otherCosts',
    isHighlightable: false,
    hasComplexRendering: false,
    searchable: true,
  },
  {
    label: 'Checked-in',
    name: 'checkedIn',
    position: 2,
    visible: true,
    sortable: true,
    editable: true,
    resizable: true,
    filterable: false,
    dataType: 'checkbox',
    fieldType: 'input',
    api: 'otherCosts',
    isHighlightable: false,
    hasComplexRendering: false,
  },
  {
    name: 'profileLink',
    label: 'Profile URL',
    position: 4,
    visible: true,
    sortable: false,
    editable: true,
    resizable: true,
    filterable: false,
    dataType: 'url',
    fieldType: 'input',
    api: 'otherCosts',
    isHighlightable: false,
    hasComplexRendering: false,
    hasImageHover: false,
    readOnly: true,
  },
  {
    label: 'Default Cost',
    name: 'cost',
    position: 3,
    visible: true,
    sortable: true,
    editable: true,
    resizable: true,
    filterable: false,
    dataType: 'currency',
    fieldType: 'input',
    api: 'otherCosts',
    isHighlightable: false,
    hasComplexRendering: false,
  },
  {
    name: 'profileImagePreview',
    label: 'Profile Image Preview',
    position: 5,
    visible: true,
    sortable: false,
    editable: false,
    resizable: true,
    filterable: false,
    dataType: 'image-url',
    fieldType: 'input',
    api: 'otherCosts',
    isHighlightable: false,
    hasComplexRendering: false,
    hasImageHover: false,
    readOnly: true,
  },
  {
    label: 'Comments',
    name: 'comments',
    position: 6,
    visible: true,
    sortable: false,
    editable: true,
    resizable: true,
    filterable: false,
    dataType: 'textarea',
    fieldType: 'textarea',
    api: 'otherCosts',
    isHighlightable: false,
    hasComplexRendering: false,
  },
  {
    label: 'Last Modified',
    name: 'lastModified',
    position: 7,
    visible: false,
    sortable: true,
    editable: false,
    resizable: true,
    filterable: true,
    dataType: 'date',
    fieldType: 'input',
    api: 'otherCosts',
    isHighlightable: false,
    hasComplexRendering: false,
  },
  {
    label: 'User Last Modified',
    name: 'userLastModified',
    position: 8,
    visible: true,
    sortable: true,
    editable: false,
    resizable: true,
    filterable: true,
    dataType: 'date',
    fieldType: 'input',
    api: 'otherCosts',
    isHighlightable: false,
    hasComplexRendering: false,
  },
  {
    label: 'User Id Created',
    name: 'userIdCreated',
    position: 9,
    visible: false,
    sortable: true,
    editable: true,
    resizable: true,
    filterable: false,
    dataType: 'string',
    fieldType: 'input',
    api: 'otherCosts',
    isHighlightable: false,
    hasComplexRendering: false,
  },
  {
    label: 'Progress',
    name: 'progress',
    position: 10,
    visible: true,
    sortable: false,
    editable: true,
    resizable: true,
    filterable: true,
    dataType: 'progress',
    fieldType: 'input',
    api: 'otherCosts',
    isHighlightable: false,
    hasComplexRendering: false,
    readOnly: true,
  },
  {
    label: 'User Id Modified',
    name: 'userIdModified',
    position: 11,
    visible: false,
    sortable: true,
    editable: true,
    resizable: true,
    filterable: false,
    dataType: 'date',
    fieldType: 'input',
    api: 'otherCosts',
    isHighlightable: false,
    hasComplexRendering: false,
  },
  {
    label: 'User Date Modified',
    name: 'userDateModified',
    position: 12,
    visible: false,
    sortable: true,
    editable: true,
    resizable: true,
    filterable: true,
    dataType: 'date',
    fieldType: 'input',
    api: 'otherCosts',
    isHighlightable: false,
    hasComplexRendering: false,
  },
];

export const dataTable = [
  {
    pkey: 100027,
    id: '8234567890 23456789',
    checkedIn: true,
    cost: 99.99,
    generalLedger: 100001,
    profileLink: 'https://en.wikipedia.org/wiki/React',
    profileImagePreview: 'Maintenance Materials',
    comments: 'fefefCOwdwdMMENT FOR OTHER COST',
    lastModified: '2021-08-20T08:24:30.11',
    userLastModified: '2021-08-20T08:24:30.11',
    userIdCreated: null,
    progress: 'Completed',
    userIdModified: 'isysadmin',
    userDateModified: '2021-08-20T08:24:30.11',
    url: 'https://via.placeholder.com/150',
  },
  {
    pkey: 100028,
    id: '2',
    checkedIn: false,
    cost: null,
    generalLedger: 100004,
    profileLink:
      'https://en.wikipedia.org/wiki/Wikipedia:Contents/Culture_and_the_arts',
    profileImagePreview: 'Maintenance Lubricants',
    comments: null,
    lastModified: '2021-04-01T02:44:05.247',
    userLastModified: '2021-04-01T02:44:05.247',
    userIdCreated: null,
    progress: 'Closed',
    userIdModified: 'isysadmin',
    userDateModified: '2021-04-01T02:44:05.247',
    url: 'https://via.placeholder.com/150',
  },
  {
    pkey: 100036,
    id: '2CAMASingi',
    checkedIn: false,
    cost: null,
    generalLedger: 100002,
    profileLink: 'https://en.wikipedia.org/wiki/The_arts',
    profileImagePreview: 'Maintenance Subcontractors',
    comments: null,
    lastModified: '2021-04-05T17:44:08.537',
    userLastModified: '2021-04-05T17:44:08.537',
    userIdCreated: 'isysadmin',
    progress: 'Closed',
    userIdModified: 'isysadmin',
    userDateModified: '2021-04-05T17:44:08.537',
    url: 'https://via.placeholder.com/150',
  },
  {
    pkey: 100053,
    id: 'a1',
    checkedIn: true,
    cost: 14.6,
    generalLedger: 100001,
    profileLink: 'https://en.wikipedia.org/wiki/Ceramic_art',
    profileImagePreview: 'Maintenance Materials',
    comments: 'a comment',
    lastModified: '2021-04-15T19:38:26.537',
    userLastModified: '2021-04-15T19:38:26.537',
    userIdCreated: 'isysadmin',
    progress: 'Open',
    userIdModified: 'isysadmin',
    userDateModified: '2021-04-15T19:38:26.537',
    url: 'https://via.placeholder.com/150',
  },
  {
    pkey: 100023,
    id: 'aaa',
    checkedIn: false,
    cost: 12.55,
    generalLedger: 100002,
    profileLink: 'https://en.wikipedia.org/wiki/Persian_pottery',
    profileImagePreview: 'Maintenance Subcontractors',
    comments: 'a comment',
    lastModified: '2021-03-31T21:44:01.017',
    userLastModified: '2021-03-31T21:44:01.017',
    userIdCreated: 'isysadmin',
    progress: 'Open',
    userIdModified: 'isysadmin',
    userDateModified: '2021-03-31T21:44:01.017',
    url: 'https://via.placeholder.com/150',
  },
  {
    pkey: 100001,
    id: 'bbb',
    checkedIn: true,
    cost: 5552.0,
    generalLedger: 100003,
    profileLink: 'https://en.wikipedia.org/wiki/Tangerang_prison_fire',
    profileImagePreview: 'Equipment Purchases',
    comments: 'this is a comment hey',
    lastModified: '2021-04-08T08:44:10.897',
    userLastModified: '2021-04-08T08:44:10.897',
    userIdCreated: null,
    progress: 'Closed',
    userIdModified: 'isysadmin',
    userDateModified: '2021-04-08T08:44:10.897',
    url: 'https://via.placeholder.com/150',
  },
  {
    pkey: 100024,
    id: 'bbb2',
    checkedIn: true,
    cost: 24.59,
    generalLedger: 100003,
    profileLink: 'https://en.wikipedia.org/wiki/Glodok',
    profileImagePreview: 'Equipment Purchases',
    comments: 'this is a comment hey',
    lastModified: '2021-03-31T21:44:01.017',
    userLastModified: '2021-03-31T21:44:01.017',
    userIdCreated: 'isysadmin',
    progress: 'Completed',
    userIdModified: 'isysadmin',
    userDateModified: '2021-03-31T21:44:01.017',
    url: 'https://via.placeholder.com/150',
  },
  {
    pkey: 100039,
    id: 'bbbr33',
    checkedIn: false,
    cost: 555.0,
    generalLedger: 100003,
    profileLink: 'https://en.wikipedia.org/wiki/Jakarta',
    profileImagePreview: 'Equipment Purchases',
    comments: 'this is a comment hey',
    lastModified: '2021-04-05T17:44:08.537',
    userLastModified: '2021-04-05T17:44:08.537',
    userIdCreated: null,
    progress: 'Open',
    userIdModified: 'isysadmin',
    userDateModified: '2021-04-05T17:44:08.537',
    url: 'https://via.placeholder.com/150',
  },
  {
    pkey: 100040,
    id: 'bbbr333',
    checkedIn: true,
    cost: 555.0,
    generalLedger: 100003,
    profileLink: 'https://en.wikipedia.org/wiki/Indonesia_Stock_Exchange',
    profileImagePreview: 'Equipment Purchases',
    comments: 'this is a comment hey',
    lastModified: '2021-04-05T17:44:08.537',
    userLastModified: '2021-04-05T17:44:08.537',
    userIdCreated: 'isysadmin',
    progress: 'Planned',
    userIdModified: 'isysadmin',
    userDateModified: '2021-04-05T17:44:08.537',
    url: 'https://via.placeholder.com/150',
  },
  {
    pkey: 100035,
    id: 'CAMASingi',
    checkedIn: true,
    cost: null,
    generalLedger: 100001,
    profileLink: 'https://en.wikipedia.org/wiki/Indonesia',
    profileImagePreview: 'Maintenance Materials',
    comments: null,
    lastModified: '2021-04-05T17:44:08.537',
    userLastModified: '2021-04-05T17:44:08.537',
    userIdCreated: null,
    progress: 'Completed',
    userIdModified: 'isysadmin',
    userDateModified: '2021-04-05T17:44:08.537',
    url: 'https://via.placeholder.com/150',
  },
];
